---
title: "アンチハラスメントポリシー"
---

なお、本ポリシーは以下のアンチハラスメントポリシーを参考に、一部改変したものです。

- [Tokyo.Rのアンチハラスメントポリシー](https://tokyor.connpass.com/)
- [TokyoGirls.rb アンチハラスメントポリシー](https://tinyurl.com/tokyogirlsrb-anti-harassment)
- [JCORSアンチハラスメントポリシー](https://jcors.net/anti-harassment-policy/)
- [ベイズ塾のアンチハラスメントポリシー](https://bayesjuku.connpass.com/)

なお、Discordでの議論に関しては、Discordコミュニティガイドラインが上位規定となります。

## 当ポリシーの目的と適用範囲

当ポリシーは、ゼミ生全員が楽しく、安全に集える場を維持するために策定されました。
「ゼミ生全員が楽しく、安全に集える場を維持する」という目的には、「将来もみなさんが不安や心配を感じることなく、気軽に参加できること」も含まれています。

よって、当ポリシーはゼミ授業時間内の発言や行動だけでなく、ゼミ活動に関連した参加者同士のコミュニケーションや、SNS・ブログ等での情報発信に対しても適用されます。

全てのゼミ生は、他のゼミ生からハラスメント行為を止めるように求められた場合、直ちに従わなければなりません。

## ハラスメントの観点

ハラスメント（他人を困らせる行為や嫌がらせ）の観点には、以下のような例があります。

- ジェンダー、性自認やジェンダー表現、性的指向
- 外見、身体的特徴
- 人種、民族、国籍
- 年齢
- 宗教
- 疾患、障がい
- 結婚・離婚・妊娠・出産・育児休業など個人的なライフイベント
- 持っている知識や経験
- キャリアや職位・職階などのポジション
- 研究方法や研究に対するスタンスなど

ただし、上記の観点はあくまで一例です。上記以外の観点であっても、ゼミ生が不快、不安に感じる発言や行動はハラスメントとみなされます。

## 禁止行為

小杉ゼミでは、上記の観点を含むハラスメントとなりうるすべての観点について、ゼミ生が不快感、不安感を感じる行為をとることを禁止します。具体例として、以下のような行為を禁止します：

- 攻撃的、非建設的、過剰に批判的な発言や揶揄（やゆ）
- 脅迫、ストーキング、つきまとい
- 不適切な身体的接触
- 性的な関心を引く行為（性的な画像の掲示や、性的なコスチュームの着用等）
- ジェンダーを強く意識させるコンテキストで、特定の個人をほめたたえる行為
- 発信者（発言者）の望まない写真撮影、録画、録音、SNS等での情報拡散（ただし、ハラスメント被害の記録としての撮影・録画・録音は除く）
- その他、ゼミ生全員がハラスメントであると判断した行為

性的なハラスメントについては男性から女性に対してだけではなく、女性から男性に対するハラスメントも禁止です。

## ハラスメントを受けたら、判断に迷ったら

ハラスメントを受けた場合、見かけた場合、もしくはハラスメントかどうか判断に迷った場合は、まずは小杉に相談してください（ただし小杉が加害者の場合は除く）。専修大学のハラスメント対策室（4号館1F）あるいは学生相談室（グリーントップB1F）に行って相談することもできます。躊躇する必要はありません。

ゼミ生一同は、ハラスメントに直面している参加者の心理的、身体的な安全を、全力で確保するように努めます。

また、ハラスメント行為をやめるように要請された参加者は、運営者の指示に直ちに従ってください。従っていただけない場合やハラスメントの影響の大きさによっては、当塾の関わるイベントへの参加を認めないことや、アカウントの解除（ワークスペースへの参加ができなくなる）も含めた対処をとります。

---

::: {.callout-note}
## みなさんへのお願い
わざわざ厳格なルールを定めなくとも、参加者ひとりひとりが「ちょっとだけ、相手の立場や気持ちを想像してみること」を心がければ、上記の願いは容易に叶えられるはずです。

誰もが安心して参加しやすい環境を維持するために、みなさんのご理解とご協力をよろしくお願いします。
:::

## ライセンス

本ポリシーは CC BY 4.0 のライセンス下で提供されています。

This work is licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).
